name: Swift

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master/6.0
      - master/7.0

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          - swift:5.3-focal
          - swift:5.4-focal
          - swift:5.5-focal
          - swift:5.6-focal
          - swift:5.7-focal
          - swift:5.8-focal
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
